<?php

namespace ContainerIY5dxdj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_Autocomplete_WrappedEntityTypeAutocompleter_BandAutocompleteFieldService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.autocomplete.wrapped_entity_type_autocompleter.band_autocomplete_field' shared service.
     *
     * @return \Symfony\UX\Autocomplete\Form\WrappedEntityTypeAutocompleter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-autocomplete'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EntityAutocompleterInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-autocomplete'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'WrappedEntityTypeAutocompleter.php';

        return $container->privates['ux.autocomplete.wrapped_entity_type_autocompleter.band_autocomplete_field'] = new \Symfony\UX\Autocomplete\Form\WrappedEntityTypeAutocompleter('App\\Form\\BandAutocompleteField', ($container->privates['form.factory'] ?? $container->load('getForm_FactoryService')), ($container->privates['ux.autocomplete.entity_metadata_factory'] ?? $container->load('getUx_Autocomplete_EntityMetadataFactoryService')), ($container->privates['property_accessor'] ?? $container->load('getPropertyAccessorService')), ($container->privates['ux.autocomplete.entity_search_util'] ?? $container->load('getUx_Autocomplete_EntitySearchUtilService')));
    }
}
