<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container40cb81K\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container40cb81K/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container40cb81K.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container40cb81K\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container40cb81K\App_KernelDevDebugContainer([
    'container.build_hash' => '40cb81K',
    'container.build_id' => 'cc25d629',
    'container.build_time' => 1670240119,
], __DIR__.\DIRECTORY_SEPARATOR.'Container40cb81K');
