<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'ux_entity_autocomplete' => [['alias'], ['_controller' => 'ux.autocomplete.entity_autocomplete_controller'], [], [['variable', '/', '[^/]++', 'alias', true], ['text', '/autocomplete']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'bands' => [[], ['_controller' => 'App\\Controller\\BandController::bands'], [], [['text', '/bands']], [], [], []],
    'band_category' => [[], ['_controller' => 'App\\Controller\\BandController::bandCategory'], [], [['text', '/band']], [], [], []],
    'band_listing' => [[], ['_controller' => 'App\\Controller\\BandController::bandListing'], [], [['text', '/band-listing']], [], [], []],
    'band_detail' => [['id'], ['_controller' => 'App\\Controller\\BandController::bandDetail'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/band']], [], [], []],
    'band_detail_save' => [['id'], ['_controller' => 'App\\Controller\\BandController::bandDetailSave'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/band']], [], [], []],
    'band_create' => [[], ['_controller' => 'App\\Controller\\BandController::bandCreate'], [], [['text', '/band/create']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\MusicianController::index'], [], [['text', '/']], [], [], []],
    'musicians' => [[], ['_controller' => 'App\\Controller\\MusicianController::musicians'], [], [['text', '/musicians']], [], [], []],
    'musician_category' => [[], ['_controller' => 'App\\Controller\\MusicianController::musicianCategory'], [], [['text', '/musician']], [], [], []],
    'musician_listing' => [[], ['_controller' => 'App\\Controller\\MusicianController::musicianListing'], [], [['text', '/musician-listing']], [], [], []],
    'musician_detail' => [['id'], ['_controller' => 'App\\Controller\\MusicianController::musicianDetail'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/musician']], [], [], []],
    'musician_detail_save' => [['id'], ['_controller' => 'App\\Controller\\MusicianController::musicianDetailSave'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/musician']], [], [], []],
    'musician_create' => [[], ['_controller' => 'App\\Controller\\MusicianController::musicianCreate'], [], [['text', '/musician/create']], [], [], []],
];
