<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/musician_band/public/build/runtime.3a3250a0.js',
                '/musician_band/public/build/284.74d99072.js',
                '/musician_band/public/build/469.76d9e211.js',
                '/musician_band/public/build/app.fb7ea2a3.js',
            ],
            'css' => [
                '/musician_band/public/build/app.72e8db74.css',
            ],
        ],
        'musician' => [
            'js' => [
                '/musician_band/public/build/runtime.3a3250a0.js',
                '/musician_band/public/build/284.74d99072.js',
                '/musician_band/public/build/431.43d2eafb.js',
                '/musician_band/public/build/musician.36312b71.js',
            ],
        ],
    ],
],

]];
